### ISSUE TITLE
[ERROR] import: com.day.jcr.vault.vlt.VltException: Unable to mount filesystem

### ISSUE THREAD

**Issue by vivekdhiman** [shsteimer/IntelliVault#20]
Hi,

I am not able to take pull or push to CRX repository. PFA Screenshots. 
![config](https://user-images.githubusercontent.com/7066652/38803730-ad72928a-418d-11e8-9cdf-72c60ddc2252.PNG)
![capture](https://user-images.githubusercontent.com/7066652/38803731-ada6f002-418d-11e8-8a42-208cb611eed8.PNG)

**Comment by ghost** [comment]
everything in your settings looks fine to me, and the exception you are getting is from vault, not from the plugin.  Usually, "Unable to mount filesystem" on an export indicates that the instance you are connecting to can't be reached.  You could try invoking the vlt cli directly to see if that gives you any further info.

**Comment by vivekdhiman** [comment]
Getting same error when i run through terminal.

```
C:\Users\vdhim6>vlt --credentials admin:admin co --force http://localhost:4502/crx
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
Checkout http://localhost:4502/crx/server/-/jcr:root/ with local files using root at C:\Users\vdhim6\jcr_root
Connecting via JCR remoting to http://localhost:4502/crx/server
[ERROR] checkout: com.day.jcr.vault.vlt.VltException: Unable to mount filesystem
caused by: javax.jcr.ItemNotFoundException: Not Found
  caused by: org.apache.jackrabbit.webdav.DavException: Not Found
```

**Comment by SSTEI43** [comment]
under the covers, the plugin is just shelling out to VTL, so if it doesn't work there, it's not going to work through the plugin.  The only time I've ever seen an issue like that is when the repo isn't running or otherwise isn't accessible for some reason, so I'm not sure why VLT can't connect to it, but it's not really an issue I can resolve in the plugin code.

**Comment by shsteimer** [comment]
under the covers, the plugin is just shelling out to VTL, so if it doesn't work there, it's not going to work through the plugin. The only time I've ever seen an issue like that is when the repo isn't running or otherwise isn't accessible for some reason, so I'm not sure why VLT can't connect to it, but it's not really an issue I can resolve in the plugin code.
